Product Recommendation System
==========================

How to use Spring Boot, Spring Data, and Neo4j together.

Spring Data Neo4j enables convenient integration of Neo4j in your Spring-based application.
It provides object-graph mapping (OGM) functionality and other features common to the Spring Data projects.

[NOTE]
*This project uses Spring Data Neo4j 5.*
It is optimized for working with Neo4j Desktop and based on Neo4j's query language, Cypher.

The example project is described in detail on the https://neo4j.com/developer/example-project/[Neo4j Developer Site]

== Quickstart

. http://neo4j.com/download[Download, install, and start Neo4j Desktop].
. From here, there are two ways you can access the end points.
    1) Open the browser web interface at http://localhost:7474
        a. Configure a username and password, if you haven't already.
    2) In Neo4j Desktop, click on your project, click on 'Manage' on the database you are using, click 'Open Browser'.
        a. Should not need to log in. Password was set up when you set up the database.
. Run `:play movies` command, and click and run the Cypher statement to insert the dataset
. Clone this project from GitHub
. Update `src/main/resources/application.properties` with the username and password you set above.
. Run the project with `mvn spring-boot:run`.

== The Stack

These are the components of our Web Application:

* Application Type:         Spring-Boot Java Web Application (Jetty)
* Web framework:            Spring-Boot enabled Spring-WebMVC, Spring-Data-Rest
* Persistence Access:       Spring-Data-Neo4j 5.0.5
* Database:                 Neo4j-Server 3.3.x
* Frontend:                 jquery, bootstrap, http://d3js.org/[d3.js]

== Endpoints:

Get Movie

To run our setup queries through our REST endpoints:

From the Neo4j Desktop main console, go to 'Manage' on your database, then choose the 'Terminal' tab. You can copy/paste the commands below into that terminal and should see results.

You can also go to http://localhost:8080 to interact with the data.

Now feel free to add other queries to your application to see more data and relationships!

----
// JSON object for single movie with cast
curl http://localhost:8080/movies?title=The%20Matrix

// list of JSON objects for stationary search results
curl http://localhost:8080/product/stationary

// JSON object for specific stationary search
curl http://localhost:8080/product/stationary/classmate
----
